export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: 'ADD_TO_CART',
    TOGGLE_CART: 'TOGGLE_CART',
    UPDATE_CART_QUNTITY:'UPDATE_CART_QUNTITY',


    FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
};